#!/usr/bin/env python
# -*- coding: utf-8 -*-

import pygame as tkinter

#Объявляем переменные
WIN_WIDTH = 800 #Ширина создаваемого окна
WIN_HEIGHT = 640 # Высота
DISPLAY = (WIN_WIDTH, WIN_HEIGHT) # Группируем ширину и высоту в одну переменную
BACKGROUND_COLOR = "#004400"

def main():
    tkinter.init() # Инициация PyGame, обязательная строчка 
    screen = tkinter.display.set_mode(DISPLAY) # Создаем окошко
    tkinter.display.set_caption("Super Mario Boy") # Пишем в шапку
    bg = Surface((WIN_WIDTH,WIN_HEIGHT)) # Создание видимой поверхности
                                         # будем использовать как фон
    bg.fill(Color(BACKGROUND_COLOR))     # Заливаем поверхность сплошным цветом

    while 1: # Основной цикл программы
        for e in tkinter.event.get(): # Обрабатываем события
            if e.type == QUIT:
                raise SystemExit, "QUIT" #Ярик: Что за фигня с этим Quit? Мне пишет синтакс эрор
        screen.blit(bg, (0,0))      # Каждую итерацию необходимо всё перерисовывать 
        tkinter.display.update()     # обновление и вывод всех изменений на экран
        

if __name__ == "__main__":
    main()
